# Generated by Django 4.0.1 on 2022-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekmit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='profit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='revenue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
